---
title: "Analysis of Manhattan Rent & Neighborhoods"
author: "Peter Bitalvo, William Johnston, Youkta Rai"
format: html
editor: visual
---

## Introduction

Over the past decade, data analytics has become an essential tool for understanding real estate markets, especially in massive complex markets like New York City. For example, rental prices are influenced by a wide range of factors like income accessibility, amenities, neighborhood, and so much more. While there are many contribution factors, it’s difficult to determine which of these truly drive rental prices, and how they interact with one another.

This project’s goal is to analyze what features best influences apartment rental prices across New York City. In particular, the goal is to identify which economic, geographic, and lifestyle factors are most strongly associated with the expected asking rent of an individual apartment. We analyzed features on both the individual apartment level and neighborhood level to quantify how much individual apartment features impact pricing compared to the neighborhood’s community characteristics.

To address this question, a wide range of data was collected at both the apartment and neighborhood levels. At the apartment level, features such as the number of bedrooms and bathrooms, as well as building amenities like in-unit laundry and doorman services, were included. At the neighborhood level, more general characteristics were gathered, including average apartment sale prices, measures of neighborhood safety, school quality, and accessibility factors such as ease of movement, transportation options, and distance from downtown measured as the distance from the world trade center.  For the statistical methods, we implemented LASSO regression, random forest regression, and multilinear regressions. The use of regularization was considered, and feature selection was heavily influenced by random forests to find the most important predictors of rent,and by using the multilinear regression to find the relationship of the features to rents.

The goal of this analysis is to better understand the key drivers of rental pricing in New York City and determine whether factors such as accessibility and amenities have a measurable impact beyond basic economic indicators like income and property values.

## Data Overview

To answer our original questions, we had to gather a wide range of data which we categorized into two sections: The neighborhood dataset, and the apartment dataset. The neighborhood dataset acts as a supplement to the apartment dataset which the project is mainly based on. It contains aggregated information from 37 neighborhoods across New York City, with each row representing a new area.

The neighborhood data began with determining a set of features that were “must-have” and “nice-to-have.” Within the “must-have” category, we identified subway accessibility and restaurant/nightlife density as essential variables. These features were selected because they capture two critical aspects of living in a large city: mobility and amenities. Areas with greater access to subway stations are typically more desirable due to increased ease of transportation, while neighborhoods with a higher concentration of restaurants and nightlife options tend to offer more leisure opportunities, which can contribute to higher demand and, ultimately, higher rental prices. More features like walk and transit scores, green space availability, median household income, school district quality, and average rent were also collected and categorized as “nice-to-have” variables. While these factors provide useful context and may influence rental prices, they were not completely essential to the models we planned on running. They were included to improve the models and capture broad characteristics of neighborhood quality, allowing us to determine if these characteristics add actual explanatory power beyond the features listed in the “must-have” category. Because this analysis included many different data sources the next step was to figure out how to join each feature to a common item. Most datasets included a neighborhood name, so this was the common denominator when cleaning and appending into a final neighborhood data frame.

It's important to note that neighborhood names are not recorded the same across the datasets we had gathered. This proved to be a difficult obstacle when cleaning and creating the final neighborhood data set. For example, the dataset for average asking rent used names such as "Chelsea" and "Murray Hill Kips Bay" while the dataset for school information used "Chelsea/Clinton" or "Murray Hill/Stuyvesant" because school districts are recorded differently. To address this issue, neighborhood names were standardized across all datasets using a combination of automated cleaning and targeted mapping. This process involved changing all names to the same format (lowercase, removing punctuation, and trimming spaces), as well as splitting combined neighborhood names where needed. For example, rows like “Chelsea/Clinton” were separated into individual neighborhoods to match with other datasets.

In addition to the automated cleaning, a small number of issues were fixed using targeted mappings to match similar or overlapping neighborhood definitions. The rent dataset was used as the base reference, or "truth", and other datasets were adjusted to match its naming structure as closely as possible. This approach helped achieve an impactful increase in overlap between datasets (from 9 common names to 37) so they could be joined together. Once standardized, the datasets were successfully merged using the neighborhood field, and values were aggregated when needed to make a consistent neighborhood-level dataset for analysis.

The dataset used in this analysis has several key strengths that make it useful for regression analysis. First, it combines information from multiple categories, which creates a more comprehensive view of neighborhood characteristics. By incorporating economic, geographic, and amenity-based variables, the dataset doesn’t become siloed into just an economic analysis or just a geographic analysis but looks at a multitude of factors that may influence rental prices. Additionally, the use of feature engineering to create composite scores (like movement, restaurant, and green space indices) helps reduce complexity and makes the data more useable. The final dataset also covers a large area of New York City, with 37 neighborhoods included in the analysis. However, the dataset also has several limitations. As mentioned before, one major challenge is the inconsistency in how neighborhoods are defined across different data sources, which require significant cleaning and mapping. While this process improved the number of neighborhoods covered, it introduced some degree of overlap when aligning different geographic definitions. The lines between neighborhoods are not perfectly defined. Additionally, some variables contained missing data, which reduced the number of usable observations in certain models and may impact the reliability of those results. For example, the green score didn’t contain neighborhood level data. To solve this issue, the median green score of each borough was taken and applied to its neighborhoods.

## Methodology

Here...

Methodology for Neighborhood analysis below…can cut down if need be

The goal of the neighborhood level analysis was to identify which characteristics best predict rental prices across New York City neighborhoods. Given the high number of variables collected and the likelihood of correlation between them, we used a multi-step modeling approach to isolate the most important predictors. The first step in our analysis was to run a LASSO regression model which we chose because it performs both variable selection and regularization. This allowed us to choose a subset of meaningful predictors from the larger group of potentially correlated variables. The LASSO results showed that only a few variables, such as median income, market sale price per unit, bike score, early education enrollment, and total green acers contributed meaningful explanatory power, while most others were effectively removed.

One result that surprised us was the total green acers having a negative lambda of -5.235, but upon closer inspection this makes sense. The most expensive rent prices are in Manhattan, and the green space data includes all boroughs in NYC. Boroughs like Staten Island and Brooklyn have lower rents than Manhattan because of more supply and less demand for apartments, but these places also have more green space overall. This led us to the conclusion that green space is more of a location proxy to Manhattan, rather than a contribution factor to rental pricing.

Following the LASSO regression, we used liner regression models to better understand the relationships between key neighborhood features and average rental prices in those neighborhoods. The result of the second model showed that market sale price per unit was the main predictor, explaining a large portion of variation in rent (R² ≈ 0.91). However, when we included it in a multiple regression model, this variable overshadowed all others, suggesting that property sale values act as a strong proxy for many neighborhood features.

To try and isolate the effects of the underlying neighborhood features, we introduced composite scores and re-ran our model. We created a composite score for education, movement, restaurants, and green space. We also decided to exclude sale price per unit in the revised regression to see if we could maintain explanatory power with the less impactful predictors. We were pleased to see this model maintain strong explanatory power (R² ≈ 0.83) and identified median income, vacancy rate, and green space as significant predictors of rent, while movement and restaurant variables were not statistically significant. These results suggest that, beyond property values, economic conditions and broader geographic features play the most important role in determining rental prices.

## Results

Here...

```{r}
#R block for whatever we need
```

## Conclusion

Here...
